In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/omicron-covid19-variant-daily-cases/covid-variants.csv

In [2]:
# import library and load the dataset
import pandas as pd
import numpy as np

df = pd.read_csv("/kaggle/input/omicron-covid19-variant-daily-cases/covid-variants.csv")
df.head()

,location,date,variant,num_sequences,perc_sequences,num_sequences_total
0,Angola,2020-07-06,Alpha,0,0.0,3
1,Angola,2020-07-06,B.1.1.277,0,0.0,3
2,Angola,2020-07-06,B.1.1.302,0,0.0,3
3,Angola,2020-07-06,B.1.1.519,0,0.0,3
4,Angola,2020-07-06,B.1.160,0,0.0,3

In [3]:
df.shape

(100416, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100416 entries, 0 to 100415
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   location             100416 non-null  object
 1   date                 100416 non-null  object
 2   variant              100416 non-null  object
 3   num_sequences        100416 non-null  int64
 4   perc_sequences       100416 non-null  float64
 5   num_sequences_total  100416 non-null  int64
dtypes: float64(1), int64(2), object(3)
memory usage: 4.6+ MB

In [5]:
df = df.rename(columns = {"num_sequences_total" : "Total"})
df.head()

  location        date    variant  num_sequences  perc_sequences  Total
0   Angola  2020-07-06      Alpha              0             0.0      3
1   Angola  2020-07-06  B.1.1.277              0             0.0      3
2   Angola  2020-07-06  B.1.1.302              0             0.0      3
3   Angola  2020-07-06  B.1.1.519              0             0.0      3
4   Angola  2020-07-06    B.1.160              0             0.0      3

In [6]:
df_indonesia = df[df["location"]=="Indonesia"]
df_indonesia.head()

        location        date    variant  num_sequences  perc_sequences  Total
37416  Indonesia  2020-05-11      Alpha              0             0.0     11
37417  Indonesia  2020-05-11  B.1.1.277              0             0.0     11
37418  Indonesia  2020-05-11  B.1.1.302              0             0.0     11
37419  Indonesia  2020-05-11  B.1.1.519              0             0.0     11
37420  Indonesia  2020-05-11    B.1.160              0             0.0     11

In [7]:
df_indonesia.shape

(1056, 6)

In [8]:
import plotly.graph_objs as go
import plotly.express as px

In [9]:
# Grouping by the date of the case
df_ind_omi = df_indonesia.groupby('date')['Total'].sum().reset_index()
df_ind_omi.head()

         date  Total
0  2020-05-11    264
1  2020-05-25    312
2  2020-06-08    432
3  2020-06-22    480
4  2020-07-06    384

In [10]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = df_ind_omi['date'],
                         y = df_ind_omi['Total'],
                         mode = 'lines',
                         name = 'Indonesia',
                         marker_color = 'DarkBlue'))

fig.update_layout(title = '<b> Total Confirmed Omicron Cases in Indonesia from 2020 to 2022<b>',
                  title_x = 0.5,
                  title_font = dict(size = 18, color = 'Darkred'),
                  template = 'plotly_white')

fig.show()

In [11]:
# import linear regression model
from sklearn.linear_model import LinearRegression

In [12]:
import datetime as dt
omi_datetime = pd.to_datetime(df_ind_omi['date'])
df_ind_omi['datetime'] = omi_datetime
df_ind_omi['datetime']=df_ind_omi['datetime'].map(dt.datetime.toordinal)
df_ind_omi

          date  Total  datetime
0   2020-05-11    264    737556
1   2020-05-25    312    737570
2   2020-06-08    432    737584
3   2020-06-22    480    737598
4   2020-07-06    384    737612
5   2020-07-20    432    737626
6   2020-08-03    672    737640
7   2020-08-17    624    737654
8   2020-08-31    576    737668
9   2020-09-14    984    737682
10  2020-09-28    528    737696
11  2020-10-12    696    737710
12  2020-10-26   1320    737724
13  2020-11-09   1032    737738
14  2020-11-23   1968    737752
15  2020-12-07   1896    737766
16  2020-12-21   2352    737780
17  2021-01-04   3744    737794
18  2021-01-11   5448    737801
19  2021-01-25   9264    737815
20  2021-02-08   5760    737829
21  2021-02-22   4608    737843
22  2021-03-08   7224    737857
23  2021-03-22   6048    737871
24  2021-04-05   4200    737885
25  2021-04-19   4392    737899
26  2021-05-03   5952    737913
27  2021-05-17   8472    737927
28  2021-05-31  14160    737941
29  2021-06-14  15600    737955
30  2021-06-28  24984    737969
31  2021-07-12  23448    737983
32  2021-07-26  18048    737997
33  2021-08-09  24360    738011
34  2021-08-23  13320    738025
35  2021-09-06  15624    738039
36  2021-09-20   9432    738053
37  2021-10-04   6624    738067
38  2021-10-18   5832    738081
39  2021-11-01   3480    738095
40  2021-11-15   3264    738109
41  2021-11-29   3432    738123
42  2021-12-13   4800    738137
43  2021-12-27   7392    738151

In [13]:
model = LinearRegression()
model.fit(df_ind_omi[["datetime"]], df_ind_omi["Total"])

LinearRegression()

In [14]:
july = dt.date(2022,7,1)
print(july)
new_date = pd.DataFrame([july], columns=['date'])
new_date['datetime'] = pd.to_datetime(new_date['date'])
new_date['datetime']=new_date['datetime'].map(dt.datetime.toordinal)
new_date

2022-07-01

         date  datetime
0  2022-07-01    738337

In [15]:
new_date['Total'] = model.predict(new_date[["datetime"]])

In [16]:
df_ind_omi = df_ind_omi.append(new_date, ignore_index=True)
df_ind_omi

          date         Total  datetime
0   2020-05-11    264.000000    737556
1   2020-05-25    312.000000    737570
2   2020-06-08    432.000000    737584
3   2020-06-22    480.000000    737598
4   2020-07-06    384.000000    737612
5   2020-07-20    432.000000    737626
6   2020-08-03    672.000000    737640
7   2020-08-17    624.000000    737654
8   2020-08-31    576.000000    737668
9   2020-09-14    984.000000    737682
10  2020-09-28    528.000000    737696
11  2020-10-12    696.000000    737710
12  2020-10-26   1320.000000    737724
13  2020-11-09   1032.000000    737738
14  2020-11-23   1968.000000    737752
15  2020-12-07   1896.000000    737766
16  2020-12-21   2352.000000    737780
17  2021-01-04   3744.000000    737794
18  2021-01-11   5448.000000    737801
19  2021-01-25   9264.000000    737815
20  2021-02-08   5760.000000    737829
21  2021-02-22   4608.000000    737843
22  2021-03-08   7224.000000    737857
23  2021-03-22   6048.000000    737871
24  2021-04-05   4200.000000    737885
25  2021-04-19   4392.000000    737899
26  2021-05-03   5952.000000    737913
27  2021-05-17   8472.000000    737927
28  2021-05-31  14160.000000    737941
29  2021-06-14  15600.000000    737955
30  2021-06-28  24984.000000    737969
31  2021-07-12  23448.000000    737983
32  2021-07-26  18048.000000    737997
33  2021-08-09  24360.000000    738011
34  2021-08-23  13320.000000    738025
35  2021-09-06  15624.000000    738039
36  2021-09-20   9432.000000    738053
37  2021-10-04   6624.000000    738067
38  2021-10-18   5832.000000    738081
39  2021-11-01   3480.000000    738095
40  2021-11-15   3264.000000    738109
41  2021-11-29   3432.000000    738123
42  2021-12-13   4800.000000    738137
43  2021-12-27   7392.000000    738151
44  2022-07-01  16855.992768    738337

In [17]:
print(model.coef_)
print(model.intercept_)
print(model.predict(df_ind_omi[['datetime']]))

[21.96036437]
-16197293.554829294
[-2.95051804e+02  1.23932967e+01  3.19838398e+02  6.27283499e+02
  9.34728600e+02  1.24217370e+03  1.54961880e+03  1.85706390e+03
  2.16450900e+03  2.47195411e+03  2.77939921e+03  3.08684431e+03
  3.39428941e+03  3.70173451e+03  4.00917961e+03  4.31662471e+03
  4.62406981e+03  4.93151492e+03  5.08523747e+03  5.39268257e+03
  5.70012767e+03  6.00757277e+03  6.31501787e+03  6.62246297e+03
  6.92990807e+03  7.23735317e+03  7.54479828e+03  7.85224338e+03
  8.15968848e+03  8.46713358e+03  8.77457868e+03  9.08202378e+03
  9.38946888e+03  9.69691398e+03  1.00043591e+04  1.03118042e+04
  1.06192493e+04  1.09266944e+04  1.12341395e+04  1.15415846e+04
  1.18490297e+04  1.21564748e+04  1.24639199e+04  1.27713650e+04
  1.68559928e+04]

In [18]:
fig = go.Figure()

fig.add_trace(go.Scatter(x = df_ind_omi['date'],
                         y = df_ind_omi['Total'],
                         mode = 'lines',
                         name = 'Omicron in Indonesia',
                         marker_color = 'DarkBlue'))
fig.add_traces(go.Scatter(x=df_ind_omi['date'], y=model.predict(df_ind_omi[['datetime']]), name='Regression Fit'))

fig.update_layout(title = '<b> Prediction of Omicron Cases in Indonesia on July 2022<b>',
                  title_x = 0.5,
                  title_font = dict(size = 18, color = 'Darkred'),
                  template = 'plotly_white')

fig.show()